### PR TITLE
Update charm to use nginx-route relation instead of ingress relation

### PR DESCRIPTION
**Pull request by weiiwang01**
The Nginx ingress integrator charm has deprecated the ingress relation, so this PR updates our charm to use the newer nginx-route relation instead.

For more information, please visit: https://discourse.charmhub.io/t/8844

### CODE REVIEW

**Review by jnsgruk — CHANGES_REQUESTED** [review]
I think a better route here would be to support the generic `ingress` relation that `nginx` now supports (the library is associated with the traefik charm).

This nginx-route interface should then be implemented by an nginx-route operator, which allows for two setups:

- hello-kubecon <----> nginx-ingress-integrator
- hello-kubecon <----> nginx-route <----> nginx-ingress-integrator

I'm pretty sure this was the intention of the change in the ingress integrator charm, but @mthaddon should be able to confirm.

**Comment by weiiwang01** [comment]
> I think a better route here would be to support the generic `ingress` relation that `nginx` now supports (the library is associated with the traefik charm).
> 
> This nginx-route interface should then be implemented by an nginx-route operator, which allows for two setups:
> 
> * hello-kubecon <----> nginx-ingress-integrator
> * hello-kubecon <----> nginx-route <----> nginx-ingress-integrator
> 
> I'm pretty sure this was the intention of the change in the ingress integrator charm, but @mthaddon should be able to confirm.

The `ingress` relation used in the Traefik charm is not compatible with the Nginx ingress integrator charm. Their similar names are merely a coincidence. If you attempt to connect the Traefik charm to hello-kubecon, it will not function properly. To prevent confusion, we have decided to drop support for the ingress relation in the Nginx ingress integrator charm.

Although there are plans to develop a new charm to convert the `ingress` relation as expected by the Traefik charm to the `nginx-route` relation, it is not currently a top priority.

**Comment by gregory-schiano** [comment]
> > I think a better route here would be to support the generic `ingress` relation that `nginx` now supports (the library is associated with the traefik charm).
> > This nginx-route interface should then be implemented by an nginx-route operator, which allows for two setups:
> > 
> > * hello-kubecon <----> nginx-ingress-integrator
> > * hello-kubecon <----> nginx-route <----> nginx-ingress-integrator
> > 
> > I'm pretty sure this was the intention of the change in the ingress integrator charm, but @mthaddon should be able to confirm.
> 
> The `ingress` relation used in the Traefik charm is not compatible with the Nginx ingress integrator charm. Their similar names are merely a coincidence. If you attempt to connect the Traefik charm to hello-kubecon, it will not function properly. To prevent confusion, we have decided to drop support for the ingress relation in the Nginx ingress integrator charm.
> 
> Although there are plans to develop a new charm to convert the `ingress` relation as expected by the Traefik charm to the `nginx-route` relation, it is not currently a top priority.

An alternative for this PR here would be to implement the real `ingress` interface in this charm instead of (or along with) the `nginx-route`

**Comment by jnsgruk** [comment]
> > > I think a better route here would be to support the generic `ingress` relation that `nginx` now supports (the library is associated with the traefik charm).
> > > This nginx-route interface should then be implemented by an nginx-route operator, which allows for two setups:
> > > 
> > > * hello-kubecon <----> nginx-ingress-integrator
> > > * hello-kubecon <----> nginx-route <----> nginx-ingress-integrator
> > > 
> > > I'm pretty sure this was the intention of the change in the ingress integrator charm, but @mthaddon should be able to confirm.
> > 
> > 
> > The `ingress` relation used in the Traefik charm is not compatible with the Nginx ingress integrator charm. Their similar names are merely a coincidence. If you attempt to connect the Traefik charm to hello-kubecon, it will not function properly. To prevent confusion, we have decided to drop support for the ingress relation in the Nginx ingress integrator charm.
> > Although there are plans to develop a new charm to convert the `ingress` relation as expected by the Traefik charm to the `nginx-route` relation, it is not currently a top priority.
> 
> An alternative for this PR here would be to implement the real `ingress` interface in this charm instead of (or along with) the `nginx-route`

That would be my preference :)

**Comment by weiiwang01** [comment]
> > > > I think a better route here would be to support the generic `ingress` relation that `nginx` now supports (the library is associated with the traefik charm).
> > > > This nginx-route interface should then be implemented by an nginx-route operator, which allows for two setups:
> > > > 
> > > > * hello-kubecon <----> nginx-ingress-integrator
> > > > * hello-kubecon <----> nginx-route <----> nginx-ingress-integrator
> > > > 
> > > > I'm pretty sure this was the intention of the change in the ingress integrator charm, but @mthaddon should be able to confirm.
> > > 
> > > 
> > > The `ingress` relation used in the Traefik charm is not compatible with the Nginx ingress integrator charm. Their similar names are merely a coincidence. If you attempt to connect the Traefik charm to hello-kubecon, it will not function properly. To prevent confusion, we have decided to drop support for the ingress relation in the Nginx ingress integrator charm.
> > > Although there are plans to develop a new charm to convert the `ingress` relation as expected by the Traefik charm to the `nginx-route` relation, it is not currently a top priority.
> > 
> > 
> > An alternative for this PR here would be to implement the real `ingress` interface in this charm instead of (or along with) the `nginx-route`
> 
> That would be my preference :)

In that case, the hello-kubecon charm will not be able to integrate with Nginx ingress integrator charm. Instead, the hello-kubecon charm will use Traefix for ingress. Is this acceptable?

**Comment by jnsgruk** [comment]
> > > > > I think a better route here would be to support the generic `ingress` relation that `nginx` now supports (the library is associated with the traefik charm).
> > > > > This nginx-route interface should then be implemented by an nginx-route operator, which allows for two setups:
> > > > > 
> > > > > * hello-kubecon <----> nginx-ingress-integrator
> > > > > * hello-kubecon <----> nginx-route <----> nginx-ingress-integrator
> > > > > 
> > > > > I'm pretty sure this was the intention of the change in the ingress integrator charm, but @mthaddon should be able to confirm.
> > > > 
> > > > 
> > > > The `ingress` relation used in the Traefik charm is not compatible with the Nginx ingress integrator charm. Their similar names are merely a coincidence. If you attempt to connect the Traefik charm to hello-kubecon, it will not function properly. To prevent confusion, we have decided to drop support for the ingress relation in the Nginx ingress integrator charm.
> > > > Although there are plans to develop a new charm to convert the `ingress` relation as expected by the Traefik charm to the `nginx-route` relation, it is not currently a top priority.
> > > 
> > > 
> > > An alternative for this PR here would be to implement the real `ingress` interface in this charm instead of (or along with) the `nginx-route`
> > 
> > 
> > That would be my preference :)
> 
> In that case, the hello-kubecon charm will not be able to integrate with Nginx ingress integrator charm. Instead, the hello-kubecon charm will use Traefix for ingress. Is this acceptable?

Yeh, I think that's fine - and maybe even preferable!

**Comment by weiiwang01** [comment]
> > > > > > I think a better route here would be to support the generic `ingress` relation that `nginx` now supports (the library is associated with the traefik charm).
> > > > > > This nginx-route interface should then be implemented by an nginx-route operator, which allows for two setups:
> > > > > > 
> > > > > > * hello-kubecon <----> nginx-ingress-integrator
> > > > > > * hello-kubecon <----> nginx-route <----> nginx-ingress-integrator
> > > > > > 
> > > > > > I'm pretty sure this was the intention of the change in the ingress integrator charm, but @mthaddon should be able to confirm.
> > > > > 
> > > > > 
> > > > > The `ingress` relation used in the Traefik charm is not compatible with the Nginx ingress integrator charm. Their similar names are merely a coincidence. If you attempt to connect the Traefik charm to hello-kubecon, it will not function properly. To prevent confusion, we have decided to drop support for the ingress relation in the Nginx ingress integrator charm.
> > > > > Although there are plans to develop a new charm to convert the `ingress` relation as expected by the Traefik charm to the `nginx-route` relation, it is not currently a top priority.
> > > > 
> > > > 
> > > > An alternative for this PR here would be to implement the real `ingress` interface in this charm instead of (or along with) the `nginx-route`
> > > 
> > > 
> > > That would be my preference :)
> > 
> > 
> > In that case, the hello-kubecon charm will not be able to integrate with Nginx ingress integrator charm. Instead, the hello-kubecon charm will use Traefix for ingress. Is this acceptable?
> 
> Yeh, I think that's fine - and maybe even preferable!

Gotcha, I will close this PR and draft a new PR.

**Comment by gregory-schiano** [comment]
> > > > > I think a better route here would be to support the generic `ingress` relation that `nginx` now supports (the library is associated with the traefik charm).
> > > > > This nginx-route interface should then be implemented by an nginx-route operator, which allows for two setups:
> > > > > 
> > > > > * hello-kubecon <----> nginx-ingress-integrator
> > > > > * hello-kubecon <----> nginx-route <----> nginx-ingress-integrator
> > > > > 
> > > > > I'm pretty sure this was the intention of the change in the ingress integrator charm, but @mthaddon should be able to confirm.
> > > > 
> > > > 
> > > > The `ingress` relation used in the Traefik charm is not compatible with the Nginx ingress integrator charm. Their similar names are merely a coincidence. If you attempt to connect the Traefik charm to hello-kubecon, it will not function properly. To prevent confusion, we have decided to drop support for the ingress relation in the Nginx ingress integrator charm.
> > > > Although there are plans to develop a new charm to convert the `ingress` relation as expected by the Traefik charm to the `nginx-route` relation, it is not currently a top priority.
> > > 
> > > 
> > > An alternative for this PR here would be to implement the real `ingress` interface in this charm instead of (or along with) the `nginx-route`
> > 
> > 
> > That would be my preference :)
> 
> In that case, the hello-kubecon charm will not be able to integrate with Nginx ingress integrator charm. Instead, the hello-kubecon charm will use Traefix for ingress. Is this acceptable?

The support for nginx integrator will be back when we will have implemented the real "ingress" relation on it. So that's indeed fine

**Pull request closed without merging**
